language: node_js
node_js:
  - '14'
  - '12'

deploy:
  skip_cleanup: true
  provider: script
  script: "./scripts/deploy.sh"
  on:
    branch: src
    node: '14'
before_install:
  - NPM_VERSION=$(npm --version)
  - if [ "${NPM_VERSION:0:2}" = "2." ]; then npm i -g npm@latest; fi
  - npm set progress=false
  - npm prune
env:
  global:
  - secure: mqIdK/jzZAKAN1ccOd4RkaFJ46HhkZV6z5TIaJoreotA+CIX0Rp2837F4++WpIuitLataAMJiyWURbprhEdK4FW4fz6lUw8rgCK0dhc75rLtma0srX3FPW7JH7NLIuOlPeQRKSxx71Xmqbygi72azhfNJ7UqZdxTCc71CCRbz6+ZbUdWfplvc/wK9Q8fR/Z0hSIRbyFVlH/hT6DFWxZVDhK8Gf0jkBPCfhqg4EWlz18xGWxsGEQujkUnjO8P13lpKCXvV99EgytvLTs9bMJ9tS+DEEQbwznjXypSGFX6T0yEpAJcLOZblSkLOcDBmyM/ByexSS0t8nZC0YQFD8e+yjiEwNszIlcQw3oPZXyYT+nWb9XV1cU3oYBbWZiuKwVeJuGl9dKJ1CKNzGbvaBahEi4HCzMDymgWw88j0Xcg4ZcxsKLOAJg7LumcwLXEskqGSK5kI+aw/ZSim0udBfuDDOG8xn4V3M9cQxNAANgHKcsC8dXiN+ZHqGNZpAkQYOfyq48z37c6bN7RyJ4cGPK5s7aqRBltsXNL2D2xA5BTkPBWbpgXjgWtzk3FVMxLWnxu1+tFSwXIA5cqamblPhUD77/BJBQS912x5xEAlC4+QCVlJzeCeHZQOo+1Ie3vbbFRUsIc0ARhsrh6j9lLOxasHjwLS/IrCsbLGDsx+lVu3eA=
  - GIT_DEPLOY_REPO=https://$GITHUB_TOKEN@github.com/giboow/giboow.github.io.git
